<?php

namespace airmess\DispBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmsRepository extends EntityRepository
{
}
